let agents=[];
const $=id=>document.getElementById(id);
let cityTimers={from:null,to:null};
let cityRequest={from:0,to:0};
let selectedCoords={from:null,to:null};
let suggestionsState={from:[],to:[]};
let carrierFilter='Все';

async function api(url,options={}){const r=await fetch(url,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Ошибка ${r.status}`);return d}
function showLogin(){ $('loginScreen').classList.remove('hidden');$('appScreen').classList.add('hidden');$('password').focus() }
function showApp(){ $('loginScreen').classList.add('hidden');$('appScreen').classList.remove('hidden') }
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function getSelected(){return agents.find(a=>a.id===window.selectedCarrierId)}

function normalizedTransport(a){return (a.transport||[]).map(x=>String(x).toLowerCase())}
function carrierSupports(a,filter){if(filter==='Все')return true;const t=normalizedTransport(a);if(filter==='Ж/Д')return t.some(x=>x.includes('ж/д')||x.includes('жд'));if(filter==='Авто')return t.some(x=>x.includes('авто'));if(filter==='Море')return t.some(x=>x.includes('море'));if(filter==='Авиа')return t.some(x=>x.includes('авиа'));if(filter==='Мультимодальные')return t.some(x=>x.includes('море + ж/д')) || (t.some(x=>x.includes('ж/д'))&&t.some(x=>x.includes('авто')));return false}
function groupFor(a){const t=normalizedTransport(a);const rail=t.some(x=>x.includes('ж/д')||x.includes('жд')),road=t.some(x=>x.includes('авто')),sea=t.some(x=>x.includes('море')),air=t.some(x=>x.includes('авиа'));if(rail&&road)return 'Ж/Д + Авто';if(sea&&rail)return 'Море + Ж/Д';if(rail)return 'Ж/Д';if(sea)return 'Море';if(air)return 'Авиа';if(road)return 'Авто';return 'Другие'}
function setCarrier(id){const a=agents.find(x=>x.id===id);if(!a)return;window.selectedCarrierId=id;$('selectedCarrierName').textContent=a.name;$('selectedCarrierTransport').textContent=(a.transport||[]).join(' · ');const sel=$('transport');sel.innerHTML='<option value="">Выберите транспорт</option>'+(a.transport||[]).map(t=>`<option>${esc(t)}</option>`).join('');$('carrierDock').classList.remove('open');$('carrierDockButton').setAttribute('aria-expanded','false');renderCarrierGroups()}
function renderTransportFilters(){const filters=['Все','Ж/Д','Авто','Море','Авиа','Мультимодальные'];$('transportFilters').innerHTML=filters.map(f=>`<button type="button" class="transport-filter ${carrierFilter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}
function renderCarrierGroups(){const filtered=agents.filter(a=>carrierSupports(a,carrierFilter));const groups={};filtered.forEach(a=>(groups[groupFor(a)]??=[]).push(a));const order=['Ж/Д + Авто','Море + Ж/Д','Ж/Д','Море','Авиа','Авто','Другие'];$('carrierGroups').innerHTML=order.filter(g=>groups[g]?.length).map(g=>`<div class="carrier-group"><div class="group-title"><span>${esc(g)}</span><em>${groups[g].length}</em></div>${groups[g].map(a=>`<button class="carrier-item ${a.id===window.selectedCarrierId?'selected':''}" data-id="${esc(a.id)}"><span class="carrier-name">${esc(a.name)}</span><span class="carrier-contact">${esc(a.contact||'')}</span></button>`).join('')}</div>`).join('')||'<div class="empty">Для этого вида транспорта экспедиторов пока нет</div>';renderTransportFilters()}

async function citySearch(kind,value){const q=value.trim(),box=$(kind+'Suggestions');if(q.length<2){box.classList.remove('show');suggestionsState[kind]=[];return}const requestId=++cityRequest[kind];try{const data=await api('/api/cities?q='+encodeURIComponent(q)+'&country='+(kind==='from'?'CN':'RU'));if(requestId!==cityRequest[kind])return;const seen=new Set();suggestionsState[kind]=(data.results||[]).filter(c=>{const key=`${c.name}|${c.admin||''}|${c.country||''}`;if(seen.has(key))return false;seen.add(key);return true}).slice(0,6);box.innerHTML=suggestionsState[kind].map((c,i)=>`<button type="button" class="suggestion" data-kind="${kind}" data-index="${i}"><span>${esc(c.name)}</span><small>${esc(c.admin||'')} · ${esc(c.country||'')}</small></button>`).join('');box.classList.toggle('show',suggestionsState[kind].length>0)}catch{if(requestId===cityRequest[kind])box.classList.remove('show')}}
function closeSuggestions(except){['from','to'].forEach(kind=>{if(kind!==except)$(kind+'Suggestions').classList.remove('show')})}
function bindAutocomplete(kind){const input=$(kind);input.addEventListener('input',()=>{selectedCoords[kind]=null;clearTimeout(cityTimers[kind]);closeSuggestions(kind);cityTimers[kind]=setTimeout(()=>citySearch(kind,input.value),240)});input.addEventListener('focus',()=>{closeSuggestions(kind);if(input.value.trim().length>=2)citySearch(kind,input.value)});$(kind+'Suggestions').addEventListener('click',e=>{const b=e.target.closest('.suggestion');if(!b)return;const c=suggestionsState[kind][Number(b.dataset.index)];if(!c)return;input.value=c.label;selectedCoords[kind]={lat:c.lat,lon:c.lon};$(kind+'Suggestions').classList.remove('show');autoDistance()})}
async function autoDistance(){if(!selectedCoords.from||!selectedCoords.to)return;try{const r=await api(`/api/route-distance?fromLat=${selectedCoords.from.lat}&fromLon=${selectedCoords.from.lon}&toLat=${selectedCoords.to.lat}&toLon=${selectedCoords.to.lon}`);if(r.ok)$('distance').value=r.distanceKm}catch{}}
function calculate(){const w=Number($('actualWeight').value)||0,places=Math.max(1,Number($('places').value)||1),l=Number($('length').value)||0,wd=Number($('width').value)||0,h=Number($('height').value)||0,divisor=Number($('divisor').value)||6000;if(!w||!l||!wd||!h){$('result').classList.add('hidden');return alert('Заполните вес и все три габарита одного места.')}const volume=l*wd*h/1e9*places,volumetric=volume*1e6/divisor,charge=Math.max(w,volumetric);$('actualResult').textContent=w.toFixed(1)+' кг';$('volumetricResult').textContent=volumetric.toFixed(1)+' кг';$('volumeResult').textContent=volume.toFixed(3)+' м³';$('distanceResult').textContent=(Number($('distance').value)||0).toLocaleString('ru-RU')+' км';$('chargeableWeight').textContent=charge.toFixed(1)+' кг';$('weightText').textContent=w>=volumetric?'Фактический вес больше объёмного':'Объёмный вес больше фактического';$('result').classList.remove('hidden')}
async function loadWeather(){try{const r=await api('/api/weather');if(!r.ok)return;$('weatherBg').className='weather-bg weather-'+(r.type||'clear')}catch{}}
async function boot(){try{const me=await api('/api/me');if(!me.authenticated)return showLogin();agents=await api('/api/agents');renderCarrierGroups();showApp();loadWeather()}catch(e){showLogin();$('loginError').textContent=e.message}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('password').value})});$('password').value='';await boot()}catch(e){$('loginError').textContent=e.message}});
$('calculateBtn').addEventListener('click',calculate);$('carrierDockButton').addEventListener('click',()=>{const open=!$('carrierDock').classList.contains('open');$('carrierDock').classList.toggle('open',open);$('carrierDockButton').setAttribute('aria-expanded',String(open));if(open)renderCarrierGroups()});$('closeCarrier').addEventListener('click',()=>{$('carrierDock').classList.remove('open');$('carrierDockButton').setAttribute('aria-expanded','false')});$('transportFilters').addEventListener('click',e=>{const b=e.target.closest('.transport-filter');if(!b)return;carrierFilter=b.dataset.filter;renderCarrierGroups()});$('carrierGroups').addEventListener('click',e=>{const b=e.target.closest('.carrier-item');if(b)setCarrier(b.dataset.id)});$('logoutBtn').addEventListener('click',async()=>{try{await api('/api/logout',{method:'POST'})}catch{}agents=[];showLogin()});
document.addEventListener('click',e=>{if(!e.target.closest('.autocomplete-field')){closeSuggestions();}if(!e.target.closest('.carrier-dock')){$('carrierDock').classList.remove('open');$('carrierDockButton').setAttribute('aria-expanded','false')}});
bindAutocomplete('from');bindAutocomplete('to');boot();
